from . import AndijonHandler
from . import BuxoroHandler
from . import FargonaHandler
from . import JizzaxHandler
from . import NamanganHandler
from . import NavoiyHandler
from . import QashqadaryoHandler
from . import QoraqalpoqHandler
from . import SamarqandHandler
from . import SirdaryoHandler
from . import SurxondaryoHandler
from . import ToshkentShHandler
from . import ToshkentVilHandler
from . import XorazmHandler
