from . import AndijonState
from . import BuxoroState
from . import FargonaState
from . import JizzaxState
from . import NamanganState
from . import NavoiyState
from . import QashqadaryoState
from . import QoraqalpoqState
from . import SamarqandState
from . import SirdaryoState
from . import SurxondaryoState
from . import ToshkentShState
from . import ToshkentVilState
from . import XorazmState
